import Civilization from '../core-civilization/Civilization.js';

export class Spanish extends Civilization {
  people = 'Spanish';
  nation = 'Spain';
  colors = ['#fff', '#ccc', '#000'];
  leaders = [
    {
      name: 'Isabella',
      traits: {
        expansionist: true,
        civilized: false,
        militaristic: true,
      },
    },
  ];
  cityNames = [
    'Madrid',
    'Barcelona',
    'Valencia',
    'Sevilla',
    'Zaragoza',
    'Málaga',
    'Murcia',
    'Palma',
    'Las Palmas de Gran Canaria',
    'Bilbao',
    'Alicante',
    'Córdoba',
    'Valladolid',
    'Vigo',
    'Gijón',
    'Eixample',
    'Latina',
    'Carabanchel',
    'A Coruña',
    'Puente de Vallecas',
    'Sant Martí',
    'Gasteiz',
    'Granada',
    'Elche',
    'Ciudad Lineal',
    'Oviedo',
    'Santa Cruz de Tenerife',
    'Fuencarral-El Pardo',
    'Badalona',
    'Cartagena',
    'Terrassa',
    'Jerez de la Frontera',
    'Sabadell',
    'Móstoles',
    'Alcalá de Henares',
    'Pamplona',
    'Fuenlabrada',
    'Almería',
    'Leganés',
    'Donostia',
    'Sants-Montjuïc',
    'Santander',
    'Castelló de la Plana',
    'Burgos',
    'Albacete',
    'Horta-Guinardó',
    'Alcorcón',
    'Getafe',
    'Nou Barris',
    'Hortaleza',
    'San Blas-Canillejas',
    'Salamanca',
    'Tetuán de las Victorias',
    'Logroño',
    'La Laguna',
    'City Center',
    'Huelva',
    'Arganzuela',
    'Badajoz',
    'Sarrià-Sant Gervasi',
    'Sant Andreu',
    'Salamanca',
    'Chamberí',
    'Usera',
    'Tarragona',
    'Chamartín',
    'Lleida',
    'Marbella',
    'León',
    'Villaverde',
    'Cadiz',
    'Retiro',
    'Dos Hermanas',
    'Mataró',
    'Gràcia',
    'Santa Coloma de Gramenet',
    'Torrejón de Ardoz',
    'Jaén',
    'Moncloa-Aravaca',
    'Algeciras',
    'Parla',
    'Delicias',
    'Ourense',
    'Alcobendas',
    'Reus',
    'Moratalaz',
    'Ciutat Vella',
    'Torrevieja',
    'Telde',
    'Barakaldo',
    'Lugo',
    'San Fernando',
    'Girona',
    'Santiago de Compostela',
    'Cáceres',
    'Lorca',
    'Coslada',
    'Talavera de la Reina',
    'El Puerto de Santa María',
    'Cornellà de Llobregat',
    'Las Rozas de Madrid',
    'Orihuela',
    'Avilés',
    'El Ejido',
    'Guadalajara',
    'Roquetas de Mar',
    'Palencia',
    'Algorta',
    'Sant Boi de Llobregat',
    'Pozuelo de Alarcón',
    'Toledo',
    'Les Corts',
    'Pontevedra',
    'Getxo',
    'Gandia',
    'Sant Cugat del Vallès',
    'Ceuta',
    'Arona',
    'Torrent',
    'Chiclana de la Frontera',
    'Manresa',
    'San Sebastián de los Reyes',
    'Ferrol',
    'Vélez-Málaga',
    'Ciudad Real',
    'Mijas',
    'Melilla',
    'Rubí',
    'Fuengirola',
    'Benidorm',
    'Alcalá de Guadaira',
    'Ponferrada',
    'Rivas-Vaciamadrid',
    'Majadahonda',
    'Campiña',
    'Vicálvaro',
    'Zamora',
    'Sagunto',
    'Vilanova i la Geltrú',
    'Sanlúcar de Barrameda',
    'Estepona',
    'Torremolinos',
    'Villa de Vallecas',
    'La Línea de la Concepción',
    'Molina de Segura',
    'Paterna',
    'Santa Lucía',
    'Viladecans',
    'El Prat de Llobregat',
  ];
  priorityTechnologies = [
    'pottery',
    'masonry',
    'currency',
  ];
}

export default Spanish;