import Civilization from '../../core-civilization/Civilization.js';

export class American extends Civilization {
  people = 'American';
  nation = 'America';
  colors = ['#63e367', '#2f7b00', '#fff'];
  leaders = [
    {
      name: 'Abraham Lincoln',
      traits: {
        expansionist: true,
        civilized: true,
        militaristic: false,
      },
    },
  ];
  cityNames = [
    'Washington',
    'New York',
    'Los Angeles',
    'Chicago',
    'Houston',
    'Phoenix',
    'Philadelphia',
    'San Antonio',
    'San Diego',
    'Dallas',
    'San Jose',
    'Austin',
    'Jacksonville',
    'Fort Worth',
    'Columbus',
    'San Francisco',
    'Charlotte',
    'Indianapolis',
    'Seattle',
    'Denver',
    'Boston',
    'El Paso',
    'Detroit',
    'Nashville',
    'Portland',
    'Memphis',
    'Oklahoma City',
    'Las Vegas',
    'Louisville',
    'Baltimore',
    'Milwaukee',
    'Albuquerque',
    'Tucson',
    'Fresno',
    'Mesa',
    'Sacramento',
    'Atlanta',
    'Kansas City',
    'Colorado Springs',
    'Miami',
    'Raleigh',
    'Omaha',
    'Long Beach',
    'Virginia Beach',
    'Oakland',
    'Minneapolis',
    'Tulsa',
    'Arlington',
    'Tampa',
    'New Orleans',
    'Wichita',
    'Cleveland',
    'Bakersfield',
    'Aurora',
    'Anaheim',
    'Honolulu',
    'Santa Ana',
    'Riverside',
    'Corpus Christi',
    'Lexington',
    'Stockton',
    'Henderson',
    'Saint Paul',
    'St. Louis',
    'Cincinnati',
    'Pittsburgh',
    'Greensboro',
    'Anchorage',
    'Plano',
    'Lincoln',
    'Orlando',
    'Irvine',
    'Newark',
    'Toledo',
    'Durham',
    'Chula Vista',
    'Fort Wayne',
    'Jersey City',
    'St. Petersburg',
    'Laredo',
    'Madison',
    'Chandler',
    'Buffalo',
    'Lubbock',
    'Scottsdale',
    'Reno',
    'Glendale',
    'Gilbert',
    'Winston–Salem',
    'North Las Vegas',
    'Norfolk',
    'Chesapeake',
    'Garland',
    'Irving',
    'Hialeah',
    'Fremont',
    'Boise',
    'Richmond',
    'Baton Rouge',
    'Spokane',
    'Des Moines',
    'Tacoma',
    'San Bernardino',
    'Modesto',
    'Fontana',
    'Santa Clarita',
    'Birmingham',
    'Oxnard',
    'Fayetteville',
    'Moreno Valley',
    'Rochester',
    'Glendale',
    'Huntington Beach',
    'Salt Lake City',
    'Grand Rapids',
    'Amarillo',
    'Yonkers',
    'Aurora',
    'Montgomery',
    'Akron',
    'Little Rock',
    'Huntsville',
    'Augusta',
    'Port St. Lucie',
    'Grand Prairie',
    'Columbus',
    'Tallahassee',
    'Overland Park',
    'Tempe',
    'McKinney',
    'Mobile',
    'Cape Coral',
    'Shreveport',
    'Frisco',
    'Knoxville',
    'Worcester',
    'Brownsville',
    'Vancouver',
    'Fort Lauderdale',
    'Sioux Falls',
    'Ontario',
    'Chattanooga',
    'Providence',
    'Newport News',
    'Rancho Cucamonga',
    'Santa Rosa',
    'Oceanside',
    'Salem',
    'Elk Grove',
    'Garden Grove',
    'Pembroke Pines',
    'Peoria',
    'Eugene',
    'Corona',
    'Cary',
    'Springfield',
    'Fort Collins',
    'Jackson',
    'Alexandria',
    'Hayward',
    'Lancaster',
    'Lakewood',
    'Clarksville',
    'Palmdale',
    'Salinas',
    'Springfield',
    'Hollywood',
    'Pasadena',
    'Sunnyvale',
    'Macon',
    'Kansas City',
    'Pomona',
    'Escondido',
    'Killeen',
    'Naperville',
    'Joliet',
    'Bellevue',
    'Rockford',
    'Savannah',
    'Paterson',
    'Torrance',
    'Bridgeport',
    'McAllen',
    'Mesquite',
    'Syracuse',
    'Midland',
    'Pasadena',
    'Murfreesboro',
    'Miramar',
    'Dayton',
    'Fullerton',
    'Olathe',
    'Orange',
    'Thornton',
    'Roseville',
    'Denton',
    'Waco',
    'Surprise',
    'Carrollton',
    'West Valley City',
    'Charleston',
    'Warren',
    'Hampton',
    'Gainesville',
    'Visalia',
    'Coral Springs',
    'Columbia',
    'Cedar Rapids',
    'Sterling Heights',
    'New Haven',
    'Stamford',
    'Concord',
    'Kent',
    'Santa Clara',
    'Elizabeth',
    'Round Rock',
    'Thousand Oaks',
    'Lafayette',
    'Athens',
    'Topeka',
    'Simi Valley',
    'Fargo',
    'Norman',
    'Columbia',
    'Abilene',
    'Wilmington',
    'Hartford',
    'Victorville',
    'Pearland',
    'Vallejo',
    'Ann Arbor',
    'Berkeley',
    'Allentown',
    'Richardson',
    'Odessa',
    'Arvada',
    'Cambridge',
    'Sugar Land',
    'Beaumont',
    'Lansing',
    'Evansville',
    'Rochester',
    'Independence',
    'Fairfield',
    'Provo',
    'Clearwater',
    'College Station',
    'West Jordan',
    'Carlsbad',
    'El Monte',
    'Murrieta',
    'Temecula',
    'Springfield',
    'Palm Bay',
    'Costa Mesa',
    'Westminster',
    'North Charleston',
    'Miami Gardens',
    'Manchester',
    'High Point',
    'Downey',
    'Clovis',
    'Pompano Beach',
    'Pueblo',
    'Elgin',
    'Lowell',
    'Antioch',
    'West Palm Beach',
    'Peoria',
    'Everett',
    'Ventura',
    'Centennial',
    'Lakeland',
    'Gresham',
    'Richmond',
    'Billings',
    'Inglewood',
    'Broken Arrow',
    'Sandy Springs',
    'Jurupa Valley',
    'Hillsboro',
    'Waterbury',
    'Santa Maria',
    'Boulder',
    'Greeley',
    'Daly City',
    'Meridian',
    'Lewisville',
    'Davie',
    'West Covina',
    'League City',
    'Tyler',
    'Norwalk',
    'San Mateo',
    'Green Bay',
    'Wichita Falls',
    'Sparks',
    'Lakewood',
    'Burbank',
    'Rialto',
    'Allen',
    'El Cajon',
    'Las Cruces',
    'Renton',
    'Davenport',
    'South Bend',
    'Vista',
    'Tuscaloosa',
    'Clinton',
    'Edison',
    'Woodbridge',
    'San Angelo',
    'Kenosha',
    'Vacaville',
  ];
  priorityTechnologies = [
    'alphabet',
    'writing',
    'code-of-laws',
  ];
}

export default American;