export {Colossus} from '../base-wonder-colossus/Colossus.js';
export {CopernicusObservatory} from '../base-wonder-copernicus-observatory/CopernicusObservatory.js';
export {GreatLibrary} from '../base-wonder-great-library/GreatLibrary.js';
export {GreatWall} from '../base-wonder-great-wall/GreatWall.js';
export {HangingGardens} from '../base-wonder-hanging-gardens/HangingGardens.js';
export {Lighthouse} from '../base-wonder-lighthouse/Lighthouse.js';
export {MagellansExpedition} from '../base-wonder-magellans-expedition/MagellansExpedition.js';
export {Oracle} from '../base-wonder-oracle/Oracle.js';
export {Pyramids} from '../base-wonder-pyramids/Pyramids.js';
